### ISSUE TITLE
Código fuera de README

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_2122-anonymous#10]
El fichero README debe contener únicamente el título, descripción, integrantes y objetivos. El [código](https://github.com/aigora/twE105_2122-anonymous/blob/49a1a43c42c271990fea2046b42ac64f8574c72d/README.md?plain=1#L22) debe estar contenido en un fichero independiente.

**Comment by javierduransainz** [comment]
De acuerdo muchas gracias.
