### ISSUE TITLE
Uso de windows.h

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twE105_2122-anonymous#11]
Recordad que **no** se permite el uso de cabeceras que no pertenezcan a la [librería estándar de C](https://en.wikipedia.org/wiki/C_standard_library#Header_files)

https://github.com/aigora/twE105_2122-anonymous/blob/ebe8b7df68b09e5f465fede5a24bb21d2c6415c6/juego/main.c#L4

**Comment by javierduransainz** [comment]
Ya lo hemos cambiado, gracias.
